[package]
name = "open-metrics-client"
version = "0.1.0"
authors = ["Max Inden <mail@max-inden.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
owning_ref = "0.4"
prost = "0.6"
prost-types = "0.7"

[dev-dependencies]
pyo3 = "0.13.0"
async-std = { version = "1.6.5", features = ["attributes"] }
tide = "0.15"

[build-dependencies]
prost-build = "0.6"
